name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Write key
        if: github.ref == 'refs/heads/master'
        run: |
          echo apiKey='${{ secrets.API_KEY }}' >> local.properties
          echo storePassword=${{ secrets.KEYSTORE_PASSWORD }} >> local.properties
          echo keyAlias=${{ secrets.KEYSTORE_ALIAS }} >> local.properties
          echo keyPassword='${{ secrets.KEYSTORE_ALIAS_PASSWORD }}' >> local.properties
          echo storeFile=../key.jks >> local.properties
          echo ${{ secrets.KEYSTORE }} | base64 --decode > key.jks
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-app-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            gradle-deps
      - name: Cache Gradle Build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-app-${{ github.sha }}
          restore-keys: |
            gradle-builds
      - name: Build with Gradle
        id: buildWithGradle
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew :app:assemble
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: "yasnac ci"
          path: "app/build/outputs"
